getallquestions:
    path: /questions
    controller: App\Controller\GetAllQuestionsAndChoicesController::index
    methods: [GET]

savequestion:
    path: /questions
    controller: App\Controller\SaveQuestionsAndChoicesController::index
    methods: [POST]